//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int id { get; set; }
        public string name { get; set; }
        public string password { get; set; }
        public Nullable<int> age { get; set; }
        public string real_fio { get; set; }
        public Nullable<int> id_comp { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual computers computers { get; set; }
        public virtual user_A user_A { get; set; }
    }
}
