//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace comp_club
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_A
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user_A()
        {
            this.admin = new HashSet<admin>();
        }
    
        public int id { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string fio { get; set; }
        public Nullable<System.TimeSpan> data_reg { get; set; }
        public Nullable<int> balance { get; set; }
        public Nullable<int> discount { get; set; }
        public Nullable<int> phone { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<admin> admin { get; set; }
        public virtual computers computers { get; set; }
    }
}
